name: Test and build

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
    paths-ignore:
      - 'releases/**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install poetry
        run: pip install poetry

      - name: Install dependencies
        run: |
          poetry config virtualenvs.in-project true
          poetry install --no-root --with dev,test

      - name: Run style checks
        run: |
          poetry run mypy .
          poetry run isort . --check --diff
          poetry run flake8 .
          poetry run black . --check --diff

      - name: Run tests
        run: poetry run pytest

  build:
    needs: [test]
    secrets: inherit
    # Replace build_web.yaml to build_lib.yaml for lib workflow
    uses: ./.github/workflows/build_lib.yaml
