name: Test and build

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
    paths-ignore:
      - 'releases/**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/test.yaml

  build:
    needs: [test]
    uses: ./.github/workflows/build_web.yaml
